Exp:
  out_dir: "saved_models/rsna/barlow/without_pretrained"
  gpu: 0

Model:
  network: "barlow"  # siamese, latent diffusion models, siamese_latent_diffusion
  mp: 1  # multiplier that controls the capacity of AE
  k : 5
  ls: 2048 #16  # the output size of encoder
  mem_dim: Null
  shrink_thres: Null

Data:
  dataset: "rsna"  # rsna, vin
  img_size: 224
  
  

Solver:
  bs: 64
  lr: 2.0e-7 # 1e-5 for DR. 10%,  after that, using 1e-6. when training with OR, always use 1e-6
  weight_decay: 0
  num_epoch: 100