Exp:
  out_dir: "saved_models/Vin/siamese"
  gpu: 0

Model:
  network: "siamese"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  k : 5
  ls: 2048 # the output size of encoder
  mem_dim: Null
  shrink_thres: Null

Data:
  dataset: "vin"  # rsna, vin
  img_size: 224
 

Solver:
  bs: 128
  lr: 1.0e-5
  weight_decay: 0
  num_epoch: 100