Exp:
  out_dir: "saved_models/Vin/AE"
  gpu: 0

Model:
  network: "AE"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  ls: 16  # the output size of encoder
  mem_dim: Null
  shrink_thres: Null

Data:
  dataset: "vin"  # rsna, vin
  img_size: 64
   

Solver:
  bs: 64
  lr: 5.0e-4
  weight_decay: 0
  num_epoch: 250
