Exp:
  out_dir: "saved_models/Vin/barlow/without_pretrained"
  gpu: 0

Model:
  network: "barlow"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  k : 5
  ls: 2048 # the output size of encoder
  mem_dim: Null
  shrink_thres: Null

Data:
  dataset: "vin"  # rsna, vin
  img_size: 224
 

Solver:
  bs: 64
  lr: 2.0e-7
  weight_decay: 0
  num_epoch: 100